# IAM User access configuration
AWS_ACCESS_KEY="HIDDEN"
AWS_SECRET_ACCESS_KEY="HIDDEN"
AWS_REGION="HIDDEN"

# S3 Bucket for photo objects
PHOTOGALLERY_S3_BUCKET_NAME="HIDDEN"

# MySQL Configuration
RDS_DB_HOSTNAME= 'HIDDEN'
RDS_DB_USERNAME='HIDDEN'
RDS_DB_PASSWORD='HIDDEN'
RDS_DB_NAME='HIDDEN'

# DynamoDB Table
DYNAMODB_TABLE='HIDDEN'
USER_TABLE='HIDDEN'

# EC2 URL, Hash for Passcode, source email

URL_SOURCE="HIDDEN"
SERIALIZER_HASH='HIDDEN'
EMAIL_S='HIDDEN'
